id: P000514
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG10580
  title: ཆོས་བདག་བཀའ་འབུམ།
  author: ''
  volumes:
    31163440eeb04d56a1dc99f072f79fb8:
      image_group_id: I1KG10661
      title: ''
      volume_number: 1
      total_pages: 282
      base_file: v001.txt
    b7e62307961a4dccb0972b805670aab1:
      image_group_id: I1KG10662
      title: ''
      volume_number: 2
      total_pages: 314
      base_file: v002.txt
ebook_metadata:
  title: ཆོས་བདག་བཀའ་འབུམ།
  author: ''
  sku: P000514
  cover: cover.jpg
  layers:
  - pagination
